### ISSUE TITLE
ReUSRGB not working 

### ISSUE THREAD

**Issue by Silver-Crystal** [YofukashiNo/ReUSRBG#1]
![image](https://github.com/YofukashiNo/ReUSRBG/assets/133802824/73a69851-863f-43e6-b5c5-782c5740ce53)
![image](https://github.com/YofukashiNo/ReUSRBG/assets/133802824/1e60cadb-d479-4194-bce7-5cc4fc91ca98)
![image](https://github.com/YofukashiNo/ReUSRBG/assets/133802824/d43ee5fb-a94f-45fc-a1cb-5ad874865ae8)
when i tried opening settings .

**Comment by Silver-Crystal** [comment]
tried 1.57 same for that one

**Comment by yofukashino** [comment]
swd

**Comment by yofukashino** [comment]
> swd

swc*

**Comment by Silver-Crystal** [comment]
Compilation and bundling? If yes what about it T-T

**Comment by Silver-Crystal** [comment]
+ activity toggle one isn't working either
